### ISSUE TITLE
Github action fails

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-S3#10]
Fails with `Exception: Integration is invalid, according to hassfest`
See if there is a fix or remove the action

**Comment by KTibow** [comment]
Just remove it and replace it with the action of nielsfaber's scheduler component.

**Comment by robmarkcole** [comment]
This one? https://github.com/nielsfaber/scheduler-component/blob/master/.github/workflows/actions.yaml 
Requires editing

**Comment by KTibow** [comment]
It shouldn’t need any editing except removing -r requirements.txt

**Comment by robmarkcole** [comment]
sorry but I don't have the motivation to do more hacking of these actions, deleted
