### ISSUE TITLE
Implement key and bucket as minio integration

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-S3#11]
Changes:
- no config for bucket, this is supplied in service call
- key is required on service call

**Comment by robmarkcole** [comment]
@macieys can you try out branch https://github.com/robmarkcole/HASS-S3/tree/support-keys and let me know how it goes?

**Comment by macieys** [comment]
Works like a charm. Thank you very much!

**Comment by robmarkcole** [comment]
done
