### ISSUE TITLE
S3 Signed URL service?

### ISSUE THREAD

**Issue by Ramias1** [robmarkcole/HASS-S3#23]
Hi

I'm curious if you've considered adding a Signed URL service?  This would grant https access to S3 objects in private S3 buckets.

I'm looking at sending images to my devices using Home Assistant Notifications and my Haas is not exposed publicly.  I could pass a signed URL to a private S3 bucket and achieve this.

I can look at trying to add this service if you don't have cycles; just wondered if it was something considered.  Thanks

**Comment by robmarkcole** [comment]
This is a valid use case for sure - signed urls are useful for sharing secure data. They typically have an expiry which you will need to consider. I'm totally open to this functionality if you want to create a pull request?

**Comment by Ramias1** [comment]
Doing a bit more research and am wondering if this is possible as a service.  For the Signed URL, I need to generate the value then pass it on to another step in the automation.  Per this post: https://community.home-assistant.io/t/checking-service-call-result-in-script/68659/2 services don't return values.

I'm wondering if I have to go the script route and store this as a variable in one step and then retrieve it in another.

I'm still new to Home Assistant and am working on it to see if it will meet my needs.  Open to any ideas.  Thanks

**Comment by robmarkcole** [comment]
Calling the service can trigger an event with the url the payload

**Comment by Ramias1** [comment]
Could not figure out how to do a pull but I forked it and uploaded my code here if you want to take a look:

https://github.com/Ramias1/HASS-S3

**Comment by Ramias1** [comment]
Just figured out how to do a pull request.

**Comment by robmarkcole** [comment]
done
