### ISSUE TITLE
Add eu-north-1

### ISSUE THREAD

**Issue by SimonThoustrup** [robmarkcole/HASS-S3#9]
Please. :-)

**Comment by robmarkcole** [comment]
Is it a new region? 
Please create PR adding here: https://github.com/robmarkcole/HASS-S3/blob/667c15a5784bdeadcf741ec513171db9bc4efc1b/custom_components/s3/__init__.py#L25

**Comment by robmarkcole** [comment]
Added in https://github.com/robmarkcole/HASS-S3/commit/9b06899167ad04a6c483a96f98245871c438d2cc
@SimonThoustrup please test and report back, thanks

**Comment by robmarkcole** [comment]
Done
